aci-cf-controller/aci-containers-controller:
  size: 66381745
  sha: 080a85953e8506cad61b97a04bbfc143d4ad88b5
aci-cf-host-agent/aci-containers-host-agent:
  size: 62072843
  sha: 3d67839083b870a0ce2e4f7b8feff25c68e57648
aci-cf-host-agent/ovsresync:
  size: 5275616
  sha: a91ac5976f55384b8b7f1b476addbba30b2c9f10
agent-ovs/agent-ovs_1.3.0~trusty_amd64.deb:
  size: 570660
  sha: 65efe71356fd9c9797c1d18963150dc9b3545321
agent-ovs/agent-ovs_1.5.0~trusty_amd64.deb:
  size: 958714
  sha: a3e24a3fcad2820cd4d75d361de4ae55675d82c4
agent-ovs/libmodelgbp_1.3.0~trusty_amd64.deb:
  size: 109808
  sha: 805285595167743875f03e9dcd7b979bfa13a77a
agent-ovs/libmodelgbp_1.5.0~trusty_amd64.deb:
  size: 113920
  sha: 94e6afc682d364236ea92880f492577e83b8e818
agent-ovs/libopflex_1.3.0~trusty_amd64.deb:
  size: 334372
  sha: c2dd3d8c01e3e4fea606c1e48b9c3825b8a42f8f
agent-ovs/libopflex_1.5.0~trusty_amd64.deb:
  size: 295600
  sha: d5281736d13f4de8433f5875bb18aea49a9e86cd
agent-ovs/libuv1_1.8.0~trusty_amd64.deb:
  size: 57076
  sha: 9bc58ce5e960affaaf02d17edd7e4f1981c497ab
agent-ovs/openvswitch-lib_2.4.1~gbp_amd64.deb:
  size: 749296
  sha: 5a2dad8b22570dfa15119b8d43229d3c5c3ada6e
opflex-cni/opflex-agent-cni:
  size: 5888160
  sha: f35557f8dbada742d13f2cc24d74cc9668511cb8
ovs_2.6.0/openvswitch-common_2.6.0_amd64.deb:
  size: 684836
  sha: 5e49629b9cc648844861ca1e99aa64e3e3304833
ovs_2.6.0/openvswitch-switch_2.6.0_amd64.deb:
  size: 1277136
  sha: 3c929c225769e161b15c87f1dab55206a2de3890
